site_name: Modelo de Ising Cuántico
site_url: https://Kimberline019.github.io/ising-mkdocs/
site_description: Documentación del proyecto de simulación cuántica en una cadena de espines

nav:
  - Inicio: index.md
  - Código: codigo.md
  - Código: ising.md
  - Resultados: resultados.md
  - Documentación: doxygen/html/index.html
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: ["Implementaciónenpython"]
theme:
  name: material
  palette:
    scheme: default
    primary: blue
    accent: cyan
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.tabs
    - navigation.sections
    - content.code.copy

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - admonition
  - toc:
      permalink: true
  - tables
  - footnotes
  - attr_list
  - def_list

extra_javascript:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

